Repository silverstripe/silverstripe-versioned, pull requests merged in 2018-02, with the labels that each got.

#114 Update reference to TestAssetStore
  tests/php/DataDifferencerTest.php
Labels: affects/v4, change/patch, effort/easy, impact/high, type/enhancement

#118 BUG Fix doRollbackTo() writing old / unsaved version over restored version
  src/Versioned.php
  tests/php/VersionedTest.php
Labels: affects/v4, change/patch, effort/easy, impact/medium, type/bug

#119 NEW Allow CMS breadcrumb badge to be extended
  src/VersionedGridFieldItemRequest.php
Labels: affects/v4, change/minor
